import dotenv from 'dotenv'
dotenv.config()

export const env = {
  PORT: process.env.PORT,
  DB_HOST: process.env.DB_HOST,
  DB_PORT: process.env.DB_PORT,
  DB_USER: process.env.DB_USER,
  DB_PASSWORD: process.env.DB_PASSWORD,
  DB_NAME: process.env.DB_NAME,
  LLM_PROVIDER: process.env.LLM_PROVIDER,
  LLM_TIMEOUT_MS: process.env.LLM_TIMEOUT_MS,
  LLM_MAX_TOKENS: process.env.LLM_MAX_TOKENS,
  LLM_TEMPERATURE: process.env.LLM_TEMPERATURE,
  DEEPSEEK_API_KEY: process.env.DEEPSEEK_API_KEY,
  DEEPSEEK_BASE_URL: process.env.DEEPSEEK_BASE_URL,
  LLM_MODEL: process.env.LLM_MODEL,
  MCP_12306_BASE_URL: process.env.MCP_12306_BASE_URL,
  MCP_12306_API_KEY: process.env.MCP_12306_API_KEY
  , GAODE_MCP_BASE_URL: process.env.GAODE_MCP_BASE_URL
  , GAODE_MCP_API_KEY: process.env.GAODE_MCP_API_KEY
  , GAODE_WEB_BASE_URL: process.env.GAODE_WEB_BASE_URL
  , GAODE_WEB_API_KEY: process.env.GAODE_WEB_API_KEY
  , JWT_SECRET: process.env.JWT_SECRET
  , PDF_FONT_PATH: process.env.PDF_FONT_PATH
  , SILICONFLOW_API_KEY: process.env.SILICONFLOW_API_KEY
  , SILICONFLOW_BASE_URL: process.env.SILICONFLOW_BASE_URL
  , SILICONFLOW_MODEL: process.env.SILICONFLOW_MODEL
  , BAILIAN_API_KEY: process.env.BAILIAN_API_KEY
  , BAILIAN_BASE_URL: process.env.BAILIAN_BASE_URL
  , BAILIAN_MODEL: process.env.BAILIAN_MODEL
  , DEEPSEEK_MODEL: process.env.DEEPSEEK_MODEL
  , LLM_PROVIDER_CHAIN: process.env.LLM_PROVIDER_CHAIN
  , MCP_RATE_LIMIT_PER_MINUTE: process.env.MCP_RATE_LIMIT_PER_MINUTE
  , AMAP_RATE_LIMIT_PER_MINUTE: process.env.AMAP_RATE_LIMIT_PER_MINUTE
  , MCP_CACHE_TTL_SECONDS: process.env.MCP_CACHE_TTL_SECONDS
  , AMAP_CACHE_TTL_SECONDS: process.env.AMAP_CACHE_TTL_SECONDS
  , CACHE_TTL_GEO: process.env.CACHE_TTL_GEO
  , CACHE_TTL_ROUTE: process.env.CACHE_TTL_ROUTE
  , SCORE_W_TIME: process.env.SCORE_W_TIME
  , SCORE_W_PRICE: process.env.SCORE_W_PRICE
  , SCORE_W_COMFORT: process.env.SCORE_W_COMFORT
  , PENALTY_W_TRANSFER: process.env.PENALTY_W_TRANSFER
  , RISK_W_NIGHT: process.env.RISK_W_NIGHT
  , RISK_W_CROSS: process.env.RISK_W_CROSS
  , RISK_W_DISTANCE: process.env.RISK_W_DISTANCE
  , RISK_W_ONTIME: process.env.RISK_W_ONTIME
  , RISK_W_WEATHER: process.env.RISK_W_WEATHER
  , RISK_W_RUSH: process.env.RISK_W_RUSH
}
